let allSongs = [{
        name: 'Renegades',
        path: 'songs/x_ambassador_-_renegades_(z3.fm).mp3',
        img: 'img/covers/Renegades.webp',
        artist: 'X Ambassador',
        id: 0,
        active: true,
    },
    {

        name: 'Mockingbird',
        path: 'songs/Eminem-Mockingbird-(HipHopKit.com).mp3',
        img: 'img/covers/Mockingbird.webp',
        artist: 'Eminem',
        id: 1,
        active: false,
    },
    {

        name: 'Mask Off',
        path: 'songs/Mask Off.mp3',
        img: 'img/covers/Future – Mask_Off.jpg',
        artist: 'Future',
        id: 2,
        active: false,
    },
    {
        name: 'Body',
        path: 'songs/Body.mp3',
        img: 'img/covers/Body.jpg',
        artist: 'Tion Wayne, Russ Millions, Capo Plaza',
        id: 3,
        active: false,
    },
    {
        name: 'Watermelon sugar',
        path: 'songs/Watermelon Sugar.mp3',
        img: 'img/covers/Watermelon Sugar.jpg',
        artist: 'Harry Styles',
        id: 4,
        active: false,
    },
    {
        name: 'Papaoutai',
        path: 'songs/Papaoutai.mp3',
        img: 'img/covers/Stromae-Papaoutai.jpg',
        artist: 'Stromae',
        id: 5,
        active: false,
    },
    {
        name: 'Nothing Breaks Like a Heart',
        path: 'songs/Nothing Breaks Like a Heart.mp3',
        img: 'img/covers/Nothing Breaks Like a Heart.png',
        artist: 'Mark Ronson ft. Miley Cyrus',
        id: 6,
        active: false,
    },
    {
        name: 'Blinding Lights',
        path: 'songs/Blinding Lights.mp3',
        img: 'img/covers/Blinding Lights.jfif',
        artist: 'The Weekend',
        id: 7,
        active: false,
    },
]
export { allSongs }